LOCAL_PATH := device/samsung/vivalto3mveml3g

USE_CAMERA_STUB := true

# Define Headers
#TARGET_SPECIFIC_HEADER_PATH := device/samsung/vivalto3mveml3g/include


# Assert
TARGET_OTA_ASSERT_DEVICE := vivalto3mveml3g,G318HZ,SM-G318HZ

# inherit from the proprietary version
-include vendor/samsung/vivalto3mveml3g/BoardConfigVendor.mk

#Platform
TARGET_ARCH := arm
TARGET_NO_BOOTLOADER := true
TARGET_BOARD_PLATFORM := sc8830
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_VARIANT := cortex-a7
TARGET_CPU_SMP := true
ARCH_ARM_HAVE_TLS_REGISTER := true

TARGET_BOOTLOADER_BOARD_NAME := sc8830

BOARD_KERNEL_CMDLINE := console=ttyS1,115200n8
BOARD_KERNEL_BASE := 0x00000000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_KERNEL_OFFSET := 0x00008000
BOARD_RAMDISK_OFFSET := 0x01000000
BOARD_TAGS_OFFSET := 0x00000100
#BOARD_MKBOOTIMG_ARGS := --dt device/samsung/vivalto3mveml3g/dt.img

TARGET_KERNEL_SOURCE := kernel/samsung/vivalto3mveml3g
#No, not this
#TARGET_KERNEL_CONFIG := vivalto3mveml3g-dt_hw01_defconfig
TARGET_KERNEL_CONFIG := vivalto3mveml3g_hw00_defconfig

#Use file-based OTA instead
BLOCK_BASED_OTA := false

# fix this up by examining /proc/mtd on a running device
TARGET_USERIMAGES_USE_EXT4 := true
#BOARD_BOOTIMAGE_PARTITION_SIZE := 0x105c0000
BOARD_BOOTIMAGE_PARTITION_SIZE := 16384000
#BOARD_RECOVERYIMAGE_PARTITION_SIZE := 0x105c0000
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 576716800
#BOARD_SYSTEMIMAGE_PARTITION_SIZE := 1085440000
BOARD_USERDATAIMAGE_PARTITION_SIZE := 209715200
#BOARD_USERDATAIMAGE_PARTITION_SIZE := 0x105c0000
BOARD_CACHEIMAGE_PARTITION_SIZE := 69206016
BOARD_CACHEIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_FLASH_BLOCK_SIZE := 512
#BOARD_FLASH_BLOCK_SIZE := 131072
TARGET_USERIMAGES_SPARSE_EXT_DISABLED := true

# Recovery
TARGET_RECOVERY_FSTAB := $(LOCAL_PATH)/rootdir/fstab.sc8830

#Some strange strings about graphics
VSYNC_EVENT_PHASE_OFFSET_NS := 0
USE_OPENGL_RENDERER := true
BUILD_EMULATOR_OPENGL := true

#Some strange strings about audio
HAVE_HTC_AUDIO_DRIVER := true
BOARD_USES_GENERIC_AUDIO := true

